# Generated by Django 3.2 on 2023-08-03 02:28

from django.db import migrations

def init_Guest(apps,schema_editor):
    users = apps.get_model('ForumPage','User')
    users.objects.create(
        username ="Guest",
        password ="Guest@room1",
        email="Guest@guest.com"
    )

class Migration(migrations.Migration):

    dependencies = [
        ('ForumPage', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_Guest) 
    ]
