# Generated by Django 4.2.3 on 2023-07-19 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ForumPage', '0002_alter_forumroom_memberlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumroom',
            name='memberList',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
