# Generated by Django 4.2.3 on 2023-07-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumPage', '0003_alter_forumroom_memberlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('logID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('timelogged', models.DateTimeField(auto_now_add=True)),
                ('actiontype', models.CharField(choices=[('Create', 'create'), ('Read', 'read'), ('Update', 'update'), ('Delete', 'delete')], editable=False, max_length=30)),
                ('action', models.JSONField(editable=False)),
            ],
        ),
    ]
