# Generated by Django 4.2.3 on 2023-07-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumPage', '0004_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='place',
            field=models.CharField(default='empty', editable=False, max_length=100),
        ),
    ]
