# Generated by Django 4.2.3 on 2023-07-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumPage', '0005_logs_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='action',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='logs',
            name='actiontype',
            field=models.CharField(choices=[('Create', 'create'), ('Read', 'read'), ('Update', 'update'), ('Delete', 'delete')], max_length=30),
        ),
        migrations.AlterField(
            model_name='logs',
            name='logID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='place',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
