# Generated by Django 4.2.3 on 2023-07-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumPage', '0006_alter_logs_action_alter_logs_actiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
